### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by aidansteele** [aidansteele/vpcjump#1]
- [ ] Automate initial EC2 + IAM setup
- [ ] SSH certificate authority for signing host keys + user keys
- [ ] SSH certificate authority in Lambda, e.g. [Bless](https://github.com/Netflix/bless). 
- [ ] More error handling
- [ ] Change `--verbose` to `--debug` and add user-friendly progress messages
